### ISSUE TITLE
Fehler: Abfahrtszeit für depart wird nicht übernommen

### ISSUE THREAD

**Issue by DevonFrosch** [MakuCoding/ttcs-plugin#1]
Zug IC2413 ist mit Abfahrt 22:08 angekündigt gewesen:

`/train ann IC2413 22:08 Königsstein Lyndern_Hbf`

Danach gibt das Komando

`/train depart my 22:32`

folgendes aus:

> [TTCS] IC2413 fährt um 22:08 Uhr von Lyndern_Hbf ab!

Die Abfahrtszeit sollte aber 22:32 sein.

**Comment by MakuCoding** [comment]
Fehler gefunden!
In der Trains.depart(String id, int depmin, int dephour) Methode wurde durch die if Abfrage verhindert, dass die Zeit gesetzt wird falls man bei der letzten Haltestelle angelangt ist. Sollte eigentlich nur verhindern das der StopIndex über die Anzahl an stops geht.
Ein kleines = zum < dazu hat damit gereicht.
