### ISSUE TITLE
Fehler: Train rm funktioniert nicht mehr

### ISSUE THREAD

**Issue by DevonFrosch** [MakuCoding/ttcs-plugin#7]
Version: 1.0.4
Eingabe:
`train announce RE4711 15:00 Lyndern Knuffingen Kleinod`
`train rm my`

Ausgabe:
> Hilfe zu /train Command:

**Comment by MakuCoding** [comment]
Liegt daran, dass im Code nur
`case: "remove"`
`case: "rem"`
steht. "rm" werde ich gleich noch hinzufügen
