### ISSUE TITLE
Fehler: Zeitgesteuerte Ansagen für gelöschten Zug

### ISSUE THREAD

**Issue by DevonFrosch** [MakuCoding/ttcs-plugin#9]
Version: 1.0.4
Eingabe:
`train announce ICE201 15:00 Lyndern Knuffingen Kleinod`
`train remove ICE201`

Um 15:00 kommt trotzdem die Ansage, dass der Zug jetzt in Lyndern abfährt.

**Comment by MakuCoding** [comment]
Der Thread lief nach dem löschen des Zuges einfach weiter. Der wird ab sofort unterbrochen sobald der Zug gelöscht wird.
